### ISSUE TITLE
can't enter game due to (possibly) a support bug from this mod

### ISSUE THREAD

**Issue by Lyj4n** [TeamMetallurgy/Aquaculture#235] opened 2021-05-12 02:59 UTC
-- MOD aquaculture --
Details:
	Mod File: Aquaculture-1.16.5-2.1.16.jar
	Failure message: Mod aquaculture only supports biomesoplenty 13.0.0.420 or above
		Currently, biomesoplenty is 1.16.5-13.1.0.463
	Mod Version: 1.16.5-2.1.16
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

**the mod clearly stated that it required 13.0.0.420 or above, however the version of biomes o plenty that I have currently installed is way more updated than the mentioned.
either way upon facing this issue I figured it would be alot better if I reported this**
**_Note: after installing the latest forge version this happened so It could be a forge issue but I reported it here anyways_**

**Comment by sscards55** [comment] 2021-05-12 03:00
Please update Aquaculture.

**Comment by sscards55** [comment] 2021-05-12 03:10
Duplicate of #231 and #230.

**Closed** 2021-05-12 07:59 UTC
