### ISSUE TITLE
Fishing Line invisable

### ISSUE THREAD

**Issue by Hydra106** [TeamMetallurgy/Aquaculture#345] opened 2022-07-19 00:51 UTC
![image](https://user-images.githubusercontent.com/84299486/179640637-dd420c48-8451-4d1b-adab-ea4073f77b4e.png)
 

![image](https://user-images.githubusercontent.com/84299486/179640744-d2f90684-086b-443b-bad5-2fa871d45ca7.png)

**Comment by Hydra106** [comment] 2022-07-19 00:53
not using any texture pack

**Comment by Hydra106** [comment] 2022-07-19 17:17
the newest version

**Comment by Shadowclaimer** [comment] 2022-07-19 17:26
It has to be asked, are you running Optifine?

**Comment by Hydra106** [comment] 2022-07-19 17:39
no

**Comment by Lukes33** [comment] 2022-07-19 18:25
Im w the 1.9 release

**Comment by Shadowclaimer** [comment] 2022-07-19 18:58
No Optifine breaks these kinds of things regularly so its always good to check lol

**Comment by GirafiStudios** [comment] 2022-07-19 21:05
It probably broke due to the recent rendering changes.
I'm currently on vacation, but I'll take a look next week.

Also, does the fishing line for vanilla rods work?
And does it render on Aquaculture rods by default, if you don't have anythinh attached?

**Comment by theslimebee** [comment] 2022-07-21 05:40
I'm having the same issue with 1.19 Forge, it doesn't show anything even without items on the rod. It does function and I can judge it by particles but the line and bobber are invisible. They ARENT invisible when using a vanilla rod, only the mod rods. I'll keep eyes here to see about any fixes from you, thank you for looking into it when you can.

**Comment by GirafiStudios** [comment] 2022-07-24 19:24
I´m unable to reproduce this.
What Forge version are you using? (Please try updating to the latest, as that works fine for me)
Also does this happen in singleplayer or multiplayer - or both?

**Comment by HinnoZ** [comment] 2022-07-27 04:36
I am currently running on forge version 1.19-41.0.107, with the aquaculture 1.19-2.4.4. I am still experiencing this bug. The line is visible in single player, but is not in my GGserver multiplayer server.

**Comment by GamerBluez95** [comment] 2022-08-01 20:27
tambien presento el mismo error en la versin 1.19 forge optifine, alguna solucion o todavia se presenta el error?

**Comment by GirafiStudios** [comment] 2022-08-01 20:54
> tambien presento el mismo error en la versin 1.19 forge optifine, alguna solucion o todavia se presenta el error?
Nobody have provided a way to properly reproduce it, so no there is no solution yet.

**Comment by GamerBluez95** [comment] 2022-08-01 21:06
> > tambien presento el mismo error en la version 1.19 forge optifine, alguna solucion o todavia se presenta el error?
> 
> Nadie ha proporcionado una forma de reproducirlo correctamente, por lo que no hay solución todavía.

gracias por tu respuesta, pero a alguien le funciona bien para multijugador?

**Comment by GirafiStudios** [comment] 2022-08-05 17:11
Nobody have provided any useful information for this, for about 2 weeks, so I´m closing this. If somebody still have the issue, please open a new issue, with easy simple steps on how to reproduce it.
There is also a chance that it got fixed in Aquaculture 2.4.5

**Closed by GirafiStudios** 2022-08-05 17:11 UTC
