### ISSUE TITLE
mousClicked Event handler crash

### ISSUE THREAD

**Issue by Skaphegor** [TeamMetallurgy/Aquaculture#190] opened 2021-01-03 16:42 UTC
https://pastebin.com/yh8sQ2Bx

**Comment by GirafiStudios** [comment] 2021-01-03 17:15
How did you encounter this crash, and how would you reproduce it?

**Comment by Skaphegor** [comment] 2021-01-03 17:26
It just after world creation making me unable to join. 
It does not happen to a saved game.

**Comment by GirafiStudios** [comment] 2021-01-03 17:28
Can you send me your Aquaculture config?
My best guess is that you (Or whoever made the modpack) have messed with the config and accidently left some stuff in there twice - as I was able to reproduce it when doing that.

**Comment by Skaphegor** [comment] 2021-01-03 17:39
I recreated the world. Firstly, this crash appeared. https://pastebin.com/D89m5bKm
Then, this crash appeared: https://pastebin.com/NjHzBTip

config: https://pastebin.com/hD5Uvjpz

**Comment by GirafiStudios** [comment] 2021-01-03 18:25
I've attempted a fix, could you try it out here? https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.16/61/

**Comment by Skaphegor** [comment] 2021-01-03 20:44
The first crash still happens, but I don't think it has to do something with this mod. 
Second crash is fixed and I can join. Seems to be fixed.

**Comment by Skaphegor** [comment] 2021-01-05 17:16
still throwing a nullpointer https://pastebin.com/4dguG7am

**Comment by GirafiStudios** [comment] 2021-01-05 17:32
That's not a nullpointer, that's a ConcurrentModificationException (Also called CME).
Some mod seems to be messing with data loading on world join/creation, as stuff seems to be loaded more times than it should. (Was also the case with the previous issue, I just added a workaround on my end)
Here is an attempted workaround to this issue: https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.16/62/

**Comment by Skaphegor** [comment] 2021-01-05 21:10
I would take a time to wait for this crash.
I'll be closing it for now and will reopen it if it will occur again,.

**Comment by Skaphegor** [comment] 2021-01-07 14:48
I'm running in this crash four times today trying to create a new world. That is very awkward, because it was recreation of my test world which I recreated multiple times before, without adding any mods or changing any configs. 
https://pastebin.com/MXwTm2U3

**Comment by GirafiStudios** [comment] 2021-01-07 14:58
Could you try and remove Enimatic Legacy, as that is mentioned in the crash too?

**Comment by Skaphegor** [comment] 2021-01-07 15:31
alos happens without https://pastebin.com/QXU5QU1t

**Comment by GirafiStudios** [comment] 2021-01-07 15:34
Could you try and remove FTB Chunks? It has a Mixin that messes with something related to biomes.

**Comment by Skaphegor** [comment] 2021-01-07 23:54
I took it out and it hasn't appeared yet again, but the crash tends to appear randomly, so it might came up later.

**Comment by GirafiStudios** [comment] 2021-01-07 23:57
I thought you were saying it appeared on world creation?

**Comment by Skaphegor** [comment] 2021-01-08 00:15
Yes, but it disappeared whilst I were testing and came back later. 
I'll be do some testing again tomorrow.

**Comment by GirafiStudios** [comment] 2021-01-08 00:17
Sounds good.
So the thing that is happening now, is that somehow the BiomeLoadingEvent is being loaded - while it's already being loaded (Basically just twice), causing the CME.

**Comment by GirafiStudios** [comment] 2021-01-09 14:16
Closing as the last I've heard the issue have dissapeared. Please open a new issue, if it comes back.

**Closed by GirafiStudios** 2021-01-09 14:16 UTC
