### ISSUE TITLE
Server Warning 

### ISSUE THREAD

**Issue by ButterBananas** [TeamMetallurgy/Aquaculture#213] opened 2021-02-21 01:41 UTC
I run my modded server and I can join and play just fine but this keeps popping up in my server window every second or two

[20:37:18] [Thread-1/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file C:\Users\zpalo\OneDrive\Desktop\Modded MC Server\config\aquaculture-common.toml is not correct. Correcting

**Comment by GirafiStudios** [comment] 2021-02-21 10:02
Duplicate of https://github.com/TeamMetallurgy/Aquaculture/issues/212

**Closed by GirafiStudios** 2021-02-21 10:02 UTC
