### ISSUE TITLE
Aquaculture error "Loot was empty in Biome"

### ISSUE THREAD

**Issue by Anaerin** [TeamMetallurgy/Aquaculture#329] opened 2022-05-28 20:44 UTC
Reporting as per server log request:
```
[Server thread/ERROR] [aquaculture/]: Loot was empty in Biome: terralith:temperate_highlands. Please report on Github
```
Server running using Moonlit Myths modpack

Minecraft Version: 1.18.2
Forge Version: 40.1.20
Aquaculture Version: 2.3.6
Terralith Version: 2.2.1a

**Comment by GirafiStudios** [comment] 2022-05-28 21:12
Duplicate of https://github.com/TeamMetallurgy/Aquaculture/issues/322
Solution provided on that issue as well :)

**Closed by GirafiStudios** 2022-05-28 21:12 UTC
