### ISSUE TITLE
Mod attempts to load commons-compress library in a dedicated server

### ISSUE THREAD

**Issue by russbrucks** [TeamMetallurgy/Aquaculture#316] opened 2022-03-18 21:35 UTC
The commons-compress library is a client side only library.  This mod fails when I try to run it in a stand alone server. 
Mod File: Aquaculture-1.18.2-2.3.4.jar
Failure message: Aquaculture 2 (aquaculture) has failed to load correctly
        java.lang.reflect.InvocationTargetException: null
Mod Version: 1.18.2-2.3.4
Mod Issue URL: NOT PROVIDED
Exception message: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists

[debug.log](https://github.com/TeamMetallurgy/Aquaculture/files/8307736/debug.log)

**Comment by GirafiStudios** [comment] 2022-03-18 22:13
Dupe of https://github.com/TeamMetallurgy/Aquaculture/issues/314 
Already fixed in Dev. Version will be available when possible.
Jenkins version can be used for now: https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.18/

**Closed by GirafiStudios** 2022-03-18 22:13 UTC
