### ISSUE TITLE
Modded Biome Support

### ISSUE THREAD

**Issue by zauberparacelsus** [TeamMetallurgy/Aquaculture#53] opened 2019-08-08 18:52 UTC
Would it be possible to add support for modded biomes, such as those added by Traverse or Biomes o Plenty?  Right now, you -can- catch Aquaculture's fish in modded biomes, but only freshwater fish will show up, rather than saltwater fish, desert fish, etc.

**Comment by GirafiStudios** [comment] 2019-08-08 19:18
Duplicate of https://github.com/TeamMetallurgy/Aquaculture/issues/26

**Closed by GirafiStudios** 2019-08-08 19:18 UTC
