### ISSUE TITLE
Report 

### ISSUE THREAD

**Issue by hkkl-VoeD** [TeamMetallurgy/Aquaculture#323] opened 2022-05-08 13:16 UTC
![image](https://user-images.githubusercontent.com/105157776/167297970-5f4921db-cc9f-4bf8-bfa1-ae31709e28c6.png)

**Comment by GirafiStudios** [comment] 2022-05-08 13:26
Duplicate of https://github.com/TeamMetallurgy/Aquaculture/issues/322
Problem is with how Terralith is only a datapack, shipped as a mod.

**Closed by GirafiStudios** 2022-05-08 13:26 UTC

**Comment by hkkl-VoeD** [comment] 2022-05-08 13:32
And what to do?

**Comment by GirafiStudios** [comment] 2022-05-08 13:49
> And what to do?

Read the solution in the issue I linked :)
