### ISSUE TITLE
Upgrade Aquatic mobs compat

### ISSUE THREAD

**Issue by traveldesign** [TeamMetallurgy/Aquaculture#108] opened 2020-04-11 22:46 UTC
Question for you guys. I love Aquaculture so much, but I would love it to work with Upgrade Aquatic. When I have both the mods installed, I never see any UA mobs anywhere. Any ideas? Someone told me that Aquaculture overrides vanilla fish spawning and that it's part of the reason. Thanks!

**Comment by sscards55** [comment] 2020-04-12 00:18
> They would have to add support on their end. We provide an API for them to use for that very purpose.
- GirafiStudios
Duplicate of #107

**Comment by GirafiStudios** [comment] 2020-04-12 06:51
We do not override anything, we simply add new fish spawns as if they were a vanilla fish. Due to there being more fish spawns it'll obviously make vanilla fish rarer, and fish from other mods.
If the fish don't spawn at all in Aquatic Upgrade it must be on their end as we do nothing to prohibit it.

**Closed by GirafiStudios** 2020-04-12 06:51 UTC
