### ISSUE TITLE
Clientside Crash - Player Kicked From Server

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TeamMetallurgy/Aquaculture#49] opened 2018-11-11 20:05 UTC
[14:02:09] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /192.168.1.7:55118
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at net.minecraft.util.FoodStats.func_151686_a(SourceFile:32) ~[afp.class:?]
        at com.teammetallurgy.aquaculture.items.meta.SubItemFood.onEaten(SubItemFood.java:85) ~[SubItemFood.class:?]
        at com.teammetallurgy.aquaculture.items.meta.MetaItemFood.func_77654_b(MetaItemFood.java:60) ~[MetaItemFood.class:?]
        at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:222) ~[aip.class:?]
        at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2781) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1125) ~[oq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2680) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2090) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 9 more

**Comment by P3rf3ctXZer0** [comment] 2018-11-11 20:05
She was eating Salmon from ocean at the time.

**Comment by GirafiStudios** [comment] 2018-11-11 20:33
What mods do you have installed besides Aquaculture?
Also what version of Aquaculture do you use?

**Comment by P3rf3ctXZer0** [comment] 2018-11-11 20:43
https://github.com/P3rf3ctXZer0/MC-ZER0PACKS/releases/tag/v0034

**Comment by GirafiStudios** [comment] 2019-01-12 18:16
Should be fixed in Aquaculture 1.6.8. Should be available on CurseForge shortly.
When you get a chance to test it, please respond back with the result, since I could not actually reproduce the issue!

**Closed by GirafiStudios** 2019-01-12 18:16 UTC

**Comment by GirafiStudios** [comment] 2019-01-16 21:49
@P3rf3ctXZer0 what was the result of your testing? :)

**Comment by P3rf3ctXZer0** [comment] 2019-01-17 08:52
Seems to be working fine so far : D
