### ISSUE TITLE
 [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world

### ISSUE THREAD

**Issue by TerraSpecOp** [TeamMetallurgy/Aquaculture#364] opened 2022-09-22 20:52 UTC
Got the following error after re-joining the world.

[22:41:43] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsBoolean(JsonElement.java:153) ~[gson-2.8.9.jar%2394!/:?] {re:mixin}
	at com.teammetallurgy.aquaculture.loot.BiomeTagPredicate.serialize(BiomeTagPredicate.java:145) ~[Aquaculture-1.19.2-2.4.7.jar%23129!/:1.19.2-2.4.7] {re:classloading,pl:epic_rei_lmao:B}
	at com.teammetallurgy.aquaculture.loot.BiomeTagCheck$BiomeTagCheckSerializer.serialize(BiomeTagCheck.java:39) ~[Aquaculture-1.19.2-2.4.7.jar%23129!/:1.19.2-2.4.7] {re:classloading,pl:epic_rei_lmao:B}
	at com.teammetallurgy.aquaculture.loot.BiomeTagCheck$BiomeTagCheckSerializer.m_6170_(BiomeTagCheck.java:35) ~[Aquaculture-1.19.2-2.4.7.jar%23129!/:1.19.2-2.4.7] {re:classloading,pl:epic_rei_lmao:B}
	
Mod List:

  [✔️] advancednetherite-1.13.7-1.19.2.jar
  [✔️] AEInfinityBooster-1.19.2-1.2.0+11.jar
  [✔️] AI-Improvements-1.19-0.5.1.jar
  [✔️] almostunified-forge-1.19-0.0.6.jar
  [✔️] appleskin-forge-mc1.19-2.4.2.jar
  [✔️] appliedenergistics2-12.5.2-beta.jar
  [✔️] Aquaculture-1.19.2-2.4.7.jar
  [✔️] architectury-6.2.43-forge.jar
  [✔️] ars_elemental-1.19.2-0.5.5.2.jar
  [✔️] ars_nouveau-1.19.2-3.3.3.jar
  [✔️] AttributeFix-Forge-1.19.2-17.1.3.jar
  [✔️] AutoRegLib-1.8-54.jar
  [✔️] balm-4.5.3.jar
  [✔️] BiomesOPlenty-1.19.2-17.1.1.152.jar
  [✔️] Bookshelf-Forge-1.19.2-16.1.5.jar
  [✔️] buildinggadgets-3.16.0-build.14+mc1.19.2.jar
  [✔️] catalogue-1.6.3-1.19.jar
  [✔️] charginggadgets-1.9.0.jar
  [✔️] ChoiceTheorem's-overhauled-village-v-3-1-1.jar
  [✔️] cloth-config-8.1.77-forge.jar
  [✔️] CodeChickenLib-1.19.2-4.3.0.470-universal.jar
  [✔️] compactmachines-5.1.0.jar
  [✔️] constructionwand-1.19.1-2.8.jar
  [✔️] curios-forge-1.19.2-5.1.1.0.jar
  [✔️] Decorative+Blocks-forge-1.19.2-3.0.0.jar
  [✔️] DiagonalFences-v4.2.1-1.19.2-Forge.jar
  [✔️] DungeonsArise-1.19-2.1.51-beta.jar
  [✔️] EnchantmentDescriptions-Forge-1.19.2-13.0.4.jar
  [✔️] EnderStorage-1.19.2-2.10.1.181-universal.jar
  [✔️] everycomp-1.19.2-2.0.6.jar
  [✔️] ExplorersCompass-1.19.2-1.2.4-forge.jar
  [✔️] farmingforblockheads-forge-1.19-11.1.0.jar
  [✔️] FastLeafDecay-30.jar
  [✔️] ferritecore-5.0.1-forge.jar
  [✔️] FpsReducer2-forge-1.19.2-2.1.jar
  [✔️] FramedBlocks-6.4.0.jar
  [✔️] FriendlyFire-Forge-1.19.2-14.0.1.jar
  [✔️] ftbbackups2-forge-1.19.2-1.0.14.jar
  [✔️] geckolib-forge-1.19-3.1.19.jar
  [✔️] glassential-forge-1.19-1.2.4.jar
  [✔️] guardvillagers-1.19.2-1.5.2.jar
  [✔️] ImmersiveEngineering-1.19.2-9.0.0-153.jar
  [✔️] Incendium_v5.1.3a.jar
  [✔️] journeymap-1.19.1-5.9.0beta2-forge.jar
  [✔️] LibX-1.19.2-4.2.5.jar
  [✔️] light-overlay-7.0.1-forge.jar
  [✔️] mcjtylib-1.19-7.0.2.jar
  [✔️] mcw-bridges-2.0.3-mc1.19.jar
  [✔️] mcw-bridges-2.0.4-mc1.19.2forge.jar
  [✔️] mcw-roofs-2.2.0-mc1.19.2-forge.jar
  [✔️] mcw-windows-2.0.3-mc1.19.jar
  [✔️] Mekanism-1.19.2-10.3.3.470.jar
  [✔️] MekanismGenerators-1.19.2-10.3.3.470.jar
  [✔️] MekanismTools-1.19.2-10.3.3.470.jar
  [✔️] mininggadgets-1.13.0.jar
  [✔️] modonomicon-1.19.2-1.0.18.jar
  [✔️] moonlight-1.19.2-2.0.29.jar
  [✔️] mowlib-0.2.36.jar
  [✔️] NaturesCompass-1.19.2-1.9.7-forge.jar
  [✔️] occultism-1.19.2-1.45.2.jar
  [✔️] oculus-mc1.19.2-1.2.8.jar
  [✔️] Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.11.jar
  [✔️] Patchouli-1.19-75.jar
  [✔️] pedestals-0.2.9.jar
  [✔️] Powah-4.0.3-alpha (1).jar
  [✔️] PuzzlesLib-v4.3.4-1.19.2-Forge.jar
  [✔️] Quark-3.3-370.jar
  [✔️] railcraft-1.19.2-13.0.0-BETA-1-CI-1ebd203.jar
  [✔️] repurposed_structures_forge-6.2.2+1.19.2.jar
  [✔️] rer-2.6.1.jar
  [✔️] rftoolsbase-1.19.1-4.0.3.jar
  [✔️] RoughlyEnoughItems-9.1.537.jar
  [✔️] RoughlyEnoughItems-plugin-compatibilities-forge-9.1.530 (1).jar
  [✔️] rubidium-0.6.2.jar
  [✔️] SimplyTools-1.19.1-1.1.3.jar
  [✔️] sophisticatedbackpacks-1.19.2-3.18.21.692.jar
  [✔️] sophisticatedcore-1.19.2-0.5.6.109.jar
  [✔️] sophisticatedstorage-1.19.2-0.5.10.129.jar
  [✔️] supplementaries-1.19.2-2.2.2.jar
  [✔️] TerraBlender-forge-1.19.2-2.0.1.127.jar
  [✔️] Terralith_v2.3.3.jar
  [✔️] theoneprobe-1.19-6.2.0.jar
  [✔️] torchmaster-19.2.0.jar
  [✔️] TravelAnchors-1.19.1-4.1.0.jar
  [✔️] twilightforest-1.19-4.2.1421-universal.jar
  [✔️] waystones-forge-1.19-11.1.0.jar

After removing the mod everything works.

**Comment by Shadowclaimer** [comment] 2022-09-22 21:01
Try removing all performance related mods and see if the bug persists and then report back.

**Comment by TerraSpecOp** [comment] 2022-09-23 20:07
Same result. Also tested with 1.18
Without the mod everything works fine.

**Comment by GirafiStudios** [comment] 2022-09-23 20:20
Does this happen with only Aquaculture?

**Comment by GirafiStudios** [comment] 2022-09-25 14:32
Unable to reproduce.
Closing as not enough information have been provided.

**Closed by GirafiStudios** 2022-09-25 14:32 UTC

**Comment by TerraSpecOp** [comment] 2022-09-27 15:02
The issue is identified. The newest versions of REI are responsible, everything works with JEI in 18.2 and 19.2
