### ISSUE TITLE
Some foods can let them kicked from Server

### ISSUE THREAD

**Issue by zsn741656478** [TeamMetallurgy/Aquaculture#50] opened 2019-01-09 02:42 UTC
When my player eat some food it will be kicked from Server.
https://i.loli.net/2019/01/09/5c355fe221466.png

And I try to play Single Game. I still be kicked from Client.
This is crash-report
https://paste.dimdev.org/bijesegulu.mccrash?tdsourcetag=s_pcqq_aiomsg

My English is not well. Sry.

**Comment by GirafiStudios** [comment] 2019-01-12 18:16
Should be fixed in Aquaculture 1.6.8. Should be available on CurseForge shortly.
When you get a chance to test it, please respond back with the result, since I could not actually reproduce the issue!

**Closed by GirafiStudios** 2019-01-12 18:16 UTC
