### ISSUE TITLE
Crash report [1.16.5 / Aquaculture-1.16.5-2.1.22.jar]

### ISSUE THREAD

**Issue by Jarero** [TeamMetallurgy/Aquaculture#366] opened 2022-10-07 14:00 UTC
hello,  when i start a new world after a few minutes it crashes
[crash-2022-10-07_09.47.56-client.txt](https://github.com/TeamMetallurgy/Aquaculture/files/9734533/crash-2022-10-07_09.47.56-client.txt)
[crash-2022-10-07_09.12.11-client.txt](https://github.com/TeamMetallurgy/Aquaculture/files/9734536/crash-2022-10-07_09.12.11-client.txt)

**Comment by GirafiStudios** [comment] 2022-10-07 14:07
Does this happen with only Aquaculture 2?

**Comment by GabrielF-C** [comment] 2022-10-22 06:49
Hi, I created an issue (#307) a few months ago and I think this is the same problem.
Some null checks have been implemented, but I still get crashes when moving my mouse while loading a world.
It also sometimes crashes randomly for no apparent reason.
[crash-2022-10-22_02.26.29-client.txt](https://github.com/TeamMetallurgy/Aquaculture/files/9843737/crash-2022-10-22_02.26.29-client.txt)

**Comment by GirafiStudios** [comment] 2022-11-05 18:35
It´s most likely some sort of mod conflicts. It crashed on a call to vanillas entity render method, which is also an indication of that.

The crash reports unfortunately do not provide any useful information.
Unless a way to reproduce the issue is provided, I can´t really even start to look at it.
As it´s most likely another mod causing the crash in AQ2 & would most likely have to be fixed on their end.
Would be happy to implement a workaround though (If possible), if someone figures out what mod(s) is causing the conflict.

**Comment by GirafiStudios** [comment] 2022-12-17 10:43
Closing this, as not enough information to recreate the issue have been provided.

**Closed by GirafiStudios** 2022-12-17 10:43 UTC
