### ISSUE TITLE
Neptune’s bounty

### ISSUE THREAD

**Issue by justfabian** [TeamMetallurgy/Aquaculture#236] opened 2021-05-15 17:38 UTC
Hey guys recently I got 10 bounty chest after fishing for about 1 h and 30 mins after putting them down I was so excited to see what I got but when I opened all 10 bounty’s I got nothing literally nothing which sucks please fix this issue cuz I really like aqua culture mod and I really wanna get every tool and piece of armor in aqua culture thank you

**Comment by GirafiStudios** [comment] 2021-05-15 17:41
Duplicate of #204

**Closed by GirafiStudios** 2021-05-15 17:41 UTC
