### ISSUE TITLE
[Mod Compatibility] Quark Visual damage values show up on fishing rods | 1.11.2

### ISSUE THREAD

**Issue by Kiyaku** [TeamMetallurgy/Aquaculture#19] opened 2017-04-02 22:56 UTC
Heya,

if i'm using the Quark Visual Stats feature, the fishing rods display damage values and it overlaps with some information. 

http://i.imgur.com/SSMdVYB.png 

Wasn't sure which mod would have to "fix" this, but the vanilla, wooden and admin fishing rods don't have this issue, so i'm guessing it has something to do with how the iron/gold/diamond rods are setup? 

Quark version: 1.2-89
Aquaculture version: 1.5.0.33

Also pinging @Vazkii 

Let me know if i can provide anything that would help!

Thanks,
SC

**Comment by GirafiStudios** [comment] 2018-05-01 23:12
Caused by the Fishing Rods extending ItemTool. Will be fixed in 1.12.2 when it is out.

**Closed by GirafiStudios** 2018-05-01 23:12 UTC
